### ISSUE TITLE
No longer functional (2.16)

### ISSUE THREAD

**Issue by greatlybabled** [schubertmc/ColorCoding#1]
Been trying for a few days to get this to work, had to reduce the size of the icon.png so it fitted in the toolbar, but the automatic color changing is no longer working, any ideas how to fix it :)

**Comment by Nadzs21** [comment]
Have the same problem. The size of the icon take all the page, I can't add any card I have to delete the add-on.

**Comment by schubertmc** [comment]
The add-on has been updated and is now fully functional again. Please do a clean install to ensure proper functionality.
