### ISSUE TITLE
Doesn't work on Anki V. ⁨2.1.61

### ISSUE THREAD

**Issue by Gaphnix** [schubertmc/ColorCoding#2]
This is a great Addon with great potential. I have been looking for such an addon for more than a year now. 
Unfortunately, it doesn't work on the latest versions of Anki. 
The icon is large and prevents the editor from working correctly, and even if you resize it the words don't get coloured
I'd appreciate the help, Thanks!

@schubertmc

**Comment by schubertmc** [comment]
The add-on has been updated and is now fully functional again. Please do a clean install to ensure proper functionality. Please reach out if you encounter additional problems.
